name: Docker Build and GitHub Pages Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Simple direct build without Docker complexity
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          BASE_URL: /DilZhan-s-Portfolio/

      # Fix asset paths for GitHub Pages if needed
      - name: Fix asset paths
        run: |
          if [ -d "dist" ]; then
            # Fix asset paths in HTML files
            find dist -name "*.html" -exec sed -i 's|="/assets/|="./assets/|g' {} \;
            
            # Create 404.html for SPA routing
            cp dist/index.html dist/404.html
            
            # Print directory structure for debugging
            echo "Contents of dist directory:"
            ls -la dist/
            echo "Contents of dist/assets directory (if exists):"
            ls -la dist/assets/ || echo "Assets directory not found or empty"
          else
            echo "Error: dist directory not found!"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 